name: Deploy
on: [push]
permissions:
  contents: write
jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true

      - name: Install Wanix
        run: |
          gh api \
            repos/tractordev/wanix/actions/artifacts \
            --jq '.artifacts[] | select(.name=="wanix-build.zip") | .id' \
            > artifact_id.txt
          
          ARTIFACT_ID=$(cat artifact_id.txt)
          
          gh api \
            repos/tractordev/wanix/actions/artifacts/$ARTIFACT_ID/zip \
            --method GET \
            -H "Accept: application/vnd.github.v3+json" \
            --output artifact.zip
            
          unzip artifact.zip
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build
        run: |
          mkdir -p _public
          ./wanix export | tar -xf - -C _public

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _public